# Configuration for Read the Docs
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"

sphinx:
  configuration: docs/source/confdocs.py

formats:
  - pdf

python:
  install:
    - requirements: docs/source/requirements.txt
